 const permissions = [
  {
    role: "superAdmin",
    modules: {
      attandence: [1, 2, 3, 4],
      branch: [1, 2, 3, 4],
      company: [1, 2, 3, 4],
      department: [1, 2, 3, 4],
      employee: [1, 2, 3, 4],
      ledgerentry: [1, 2, 3, 4],
      holiday: [1, 2, 3, 4],
      leave: [1, 3, 4],
      ledger: [1, 2, 3, 4],
      notification: [1, 2, 3, 4],
      permission: [1, 2, 3, 4],
      salary: [1, 2, 3, 4],
      user: [1, 2, 3, 4],
    },
  },
  {
    role: "Admin",
    modules: {
      attandence: [1, 2, 3, 4],
      branch: [1, 2, 3],
      department: [1, 2, 3, 4],
      employee: [1, 2, 3, 4],
      ledgerentry: [1, 2, 3, 4],
      holiday: [1, 2, 3, 4],
      leave: [1, 3, 4],
      ledger: [1, 2, 3, 4],
      notification: [1, 2, 3, 4],
      salary: [1, 2, 3, 4],
      user: [1, 2, 3],
    },
  },
  {
    role: "manager",
    modules: {
      attandence: [1, 2, 3],
      branch: [1],
      department: [1, 2, 3],
      employee: [1, 2, 3],
      ledgerentry: [1, 2, 3, 4],
      holiday: [1, 2],
      leave: [1, 3],
      ledger: [1, 2, 3, 4],
      notification: [1, 2],
      salary: [1],
    },
  },
  {
    role: "employee",
    modules: {
      attandence: [1],
      holiday: [1],
      leave: [1, 2],
      notification: [1],
      salary: [1],
    },
  },
];
module.exports = permissions;